# Generated by Django 3.0.6 on 2020-08-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20200827_1824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weather_d',
            new_name='Weath',
        ),
    ]
