# Generated by Django 3.0.6 on 2020-08-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200827_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weather',
            new_name='Weather_d',
        ),
    ]
